sign-commit = true
sign-tag = true
dev-version = false
pre-release-commit-message = "Release {{version}}"
tag-prefix = ""
tag-name = "{{version}}"
pre-release-replacements = [
  {file="CHANGELOG.md", search="## \\[Unreleased\\]", replace="## [Unreleased]\n\n## {{version}} - {{date}}"},
  {file="CHANGELOG.md", search="HEAD", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\[Unreleased\\]:", replace="[Unreleased]: https://github.com/Peltoche/lsd/compare/{{version}}...HEAD\n[{{version}}]: "},
  {file="README.md", search="lsd_[0-9\\.]+_amd64.deb", replace="lsd_{{version}}_amd64.deb"},
]
